name: codematic-youtube-frontend CI/CD

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy codematic-youtube-frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script_stop: true
          command_timeout: 200m
          script: |
            # Install Docker Compose if not present
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            cd /home/projects/codematics/codematic-youtube-frontend
            git pull
            docker-compose down
            docker system prune -af
            docker-compose build --force-rm --no-cache --compress
            docker-compose up -d
            if docker-compose ps | grep -q "codematic-youtube-frontend-container"; then
              echo "Deployment successful"
            else
              echo "Deployment failed"
              exit 1
            fi
